/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesCourseIdRouteImport } from './routes/courses/$courseId'
import { Route as LessonCourseIdLessonIndexRouteImport } from './routes/lesson/$courseId.$lessonIndex'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonCourseIdLessonIndexRoute =
  LessonCourseIdLessonIndexRouteImport.update({
    id: '/lesson/$courseId/$lessonIndex',
    path: '/lesson/$courseId/$lessonIndex',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/lesson/$courseId/$lessonIndex': typeof LessonCourseIdLessonIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/lesson/$courseId/$lessonIndex': typeof LessonCourseIdLessonIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/lesson/$courseId/$lessonIndex': typeof LessonCourseIdLessonIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/courses/$courseId' | '/lesson/$courseId/$lessonIndex'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/courses/$courseId' | '/lesson/$courseId/$lessonIndex'
  id: '__root__' | '/' | '/courses/$courseId' | '/lesson/$courseId/$lessonIndex'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  LessonCourseIdLessonIndexRoute: typeof LessonCourseIdLessonIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$courseId/$lessonIndex': {
      id: '/lesson/$courseId/$lessonIndex'
      path: '/lesson/$courseId/$lessonIndex'
      fullPath: '/lesson/$courseId/$lessonIndex'
      preLoaderRoute: typeof LessonCourseIdLessonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  LessonCourseIdLessonIndexRoute: LessonCourseIdLessonIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
